# Build Stage
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Serve Stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Nginx default configuration automatically routes /
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
